version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "fraud-detection-durable-function"

[default.build]
[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "fraud-detection-durable-function"
s3_prefix = "fraud-detection-durable-function"
region = "us-east-1"
image_repositories = []
parameter_overrides = [
    "FunctionName=fn-Fraud-Detection",
    "LayerName=lr-FraudDetection", 
    "RoleName=durable-function-execution-role",
    "AgentRuntimeName=fraud_risk_scorer",
    "AgentRoleName=bedrock-agentcore-runtime-fraud-role",
    "ECRRepoName=fraud-risk-scorer",
    "LambdaRegion=us-east-1",
    "AgentRegion=us-east-1",
    "ExecutionTimeout=600",
    "RetentionPeriodInDays=7"
]